### ISSUE TITLE
facing problem this forwrd method

### ISSUE THREAD

**Issue by ghost** [denpamusic/Mint#1]
production.ERROR: exception 'ErrorException' with message 'Indirect modification of overloaded property Mint\Libraries\BitcoinConverter::$satoshi has no effect' in /var/www/html/app/Http/Controllers/API/ApiController.php:764

everything working fine. but only recevice?method=create here forward=1 i put but balance not forwarding
tnx for making this apps. its really helpfull

**Comment by ghost** [comment]
FatalErrorException in ApiController.php line 738:
syntax error, unexpected '.', expecting '&' or variable (T_VARIABLE)

seem like that in new update private function bcsum do not have any use. so its not matter

**Comment by denpamusic** [comment]
Hi!

Thank you for showing interest in this project.

At first, this app's been forked from [EzBit API](https://github.com/paxful/EzBitcoin-Api-Wallet) made by paxful with a little bit of tweaks and bugfixes. Now, with most of the code rewritten and framework(laravel) upgraded to version 5.2, Mint is a separate project which is in some areas superior and in some areas _still_ inferior to it's origin. This app will stay under heavy development for the following week to stabilize it's codebase, which is why I advice you against using it, at very least until documentation is finished.

As for your problem, please check your PHP version. This app requires at least PHP 5.6 to run. Also ensure that you're correctly using callback and blocknotify. Mint uses artisan commands for these two methods, so you must specify "walletnotify=php /var/www/html/artisan api:callback %s" and "blocknotify=php /var/www/html/artisan api:blocknotify %s" in bitcoin.conf.

Truly yours,
Denpa
